stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/Dockerfile
      buildContext: .
      tag: botflow-api:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
     registry: registry.YOUR_DOMAIN
- name: Deploy staging
  when:
    branch: devel
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment-staging.yaml
- name: Deploy production
  when:
    branch: master
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment-production.yaml
branch:
  include: [master, devel]