# Generated by Django 2.2.5 on 2019-09-03 12:29

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('samples', djongo.models.fields.DictField(default={'list': []})),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', djongo.models.fields.DictField(default={'list': []})),
            ],
        ),
        migrations.CreateModel(
            name='Utter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('possibilities', djongo.models.fields.DictField(default={'list': []})),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('intents', djongo.models.fields.ArrayReferenceField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Intent')),
                ('stories', djongo.models.fields.ArrayReferenceField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Story')),
                ('utters', djongo.models.fields.ArrayReferenceField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Utter')),
            ],
        ),
    ]
