# Generated by Django 2.2.5 on 2019-09-09 18:38

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=djongo.models.fields.ListField(default=[]),
        ),
    ]
