# Generated by Django 2.2.6 on 2019-10-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190909_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_checkpoint',
            field=models.BooleanField(default=False),
        ),
    ]
